import { useState } from "react";
import { Activity, ArrowUpRight, Download, FileText, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AiRoadBriefPanel } from "@/components/analytics/AiRoadBriefPanel";
import { LineChart, Line, ResponsiveContainer, Tooltip, PieChart, Pie, Cell } from "recharts";
import { reportsApi } from "@/api/reports";
import type { AnalyticsData, BudgetData, Project, VideoOverlayMetadata } from "@/types";

interface AnalyticsViewProps { project: Project; analytics: AnalyticsData; budget: BudgetData; video: VideoOverlayMetadata; onUpload: () => void; }

export function AnalyticsView({ project, analytics, budget, video, onUpload }: AnalyticsViewProps) {
  const [exporting, setExporting] = useState(false);
  const exportReport = async () => {
    setExporting(true);
    try { await reportsApi.download(project.id, "full"); }
    catch { alert("Could not export the PDF report."); }
    finally { setExporting(false); }
  };

  return <main data-testid="analytics-screen" className="app-screen min-h-svh bg-[#08100f] px-4 pb-10 pt-20 text-white sm:px-8 sm:pt-24"><div className="mx-auto max-w-[1250px]">
    <header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker text-[#b8e986]">Road intelligence</p><h1 data-testid="analytics-heading" className="mt-2 text-4xl font-semibold tracking-[-0.06em] sm:text-6xl">Analytics</h1><p className="mt-3 text-sm text-white/40">One model, a clearer view of what needs attention.</p></div><div className="flex gap-2"><Button data-testid="analytics-upload-button" type="button" onClick={onUpload} className="h-10 rounded-xl bg-[#b8e986] text-xs text-[#10201b] hover:bg-[#d3f5ad]"><ArrowUpRight size={14} /> Upload survey media</Button><Button data-testid="analytics-export-report-button" type="button" variant="outline" onClick={() => void exportReport()} disabled={exporting} className="h-10 rounded-xl border-white/10 bg-white/[0.04] text-xs text-white/70 hover:bg-white/10"><Download size={14} /> {exporting ? "Preparing PDF..." : "Export report"}</Button></div></header>
    <div className="grid gap-5 lg:grid-cols-[1.35fr_0.65fr]">
      <section data-testid="analytics-confidence-chart" className="glass-panel rounded-[26px] p-5 sm:p-6"><div className="flex items-start justify-between"><div><span className="section-kicker">Frame confidence</span><div className="mt-3 flex items-baseline gap-2"><span className="text-5xl font-semibold tracking-[-0.07em]">{analytics.confidence}%</span><span className="text-xs text-[#b8e986]">Current survey</span></div></div><span className="rounded-full bg-[#b8e986]/10 px-2.5 py-1 text-[10px] text-[#cbedab]">Live result</span></div><div className="mt-8 h-52"><ResponsiveContainer width="100%" height="100%"><LineChart data={analytics.roadProfile}><Line type="monotone" dataKey="value" stroke="#b8e986" strokeWidth={2.5} dot={{ r: 3, fill: "#0d1917", stroke: "#b8e986", strokeWidth: 2 }} activeDot={{ r: 5, fill: "#b8e986", stroke: "#10201b" }} /><Tooltip contentStyle={{ background: "#182421", border: "1px solid rgba(255,255,255,.12)", borderRadius: 12, color: "#fff", fontSize: 11 }} /></LineChart></ResponsiveContainer></div><div className="mt-3 flex justify-between text-[10px] text-white/30"><span>{analytics.roadProfile[0]?.label ?? "Start"}</span><span>{analytics.roadProfile[Math.floor(analytics.roadProfile.length / 2)]?.label ?? "Mid"}</span><span>{analytics.roadProfile.at(-1)?.label ?? "End"}</span></div></section>
      <section data-testid="analytics-quality-panel" className="glass-panel rounded-[26px] p-5 sm:p-6"><span className="section-kicker">Signal quality</span><div className="mt-5 flex items-center gap-6"><div className="relative h-32 w-32 shrink-0"><div className="absolute inset-0 rounded-full" style={{ background: `conic-gradient(#b8e986 ${analytics.quality * 3.6}deg, rgba(255,255,255,.08) 0deg)` }} /><div className="absolute inset-[7px] flex items-center justify-center rounded-full bg-[#16211e]"><span className="text-3xl font-semibold tracking-[-0.06em]">{analytics.quality}<small className="text-xs text-white/40">%</small></span></div></div><div><div className="flex items-center gap-2 text-sm font-medium"><ShieldCheck size={15} className="text-[#b8e986]" /> Capture quality</div><p className="mt-2 text-xs leading-5 text-white/40">Derived from image clarity, road-boundary stability and detection signals.</p></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/[0.04] p-3"><span className="block text-lg font-semibold">{analytics.defectsDetected}</span><span className="text-[10px] text-white/35">defects detected</span></div><div className="rounded-xl bg-white/[0.04] p-3"><span className="block text-lg font-semibold">{analytics.analyzedDistance.replace(" km", "")}</span><span className="text-[10px] text-white/35">km analyzed</span></div></div></section>
    </div>
    <AiRoadBriefPanel project={project} analytics={analytics} budget={budget} video={video} className="mt-5" />
    <div className="mt-5 grid gap-5 lg:grid-cols-[0.8fr_1.2fr]">
      <section data-testid="analytics-condition-panel" className="glass-panel rounded-[26px] p-5 sm:p-6"><div className="flex items-center justify-between"><span className="section-kicker">Road conditions</span><Activity size={15} className="text-white/35" /></div><div className="mt-4 flex items-center gap-5"><div className="h-40 w-40"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={analytics.conditionBreakdown} dataKey="value" innerRadius={47} outerRadius={65} paddingAngle={3} strokeWidth={0}>{analytics.conditionBreakdown.map((entry) => <Cell key={entry.label} fill={entry.color} />)}</Pie></PieChart></ResponsiveContainer></div><div className="flex-1 space-y-3">{analytics.conditionBreakdown.map((entry) => <div key={entry.label} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-white/50"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: entry.color }} />{entry.label}</span><span className="text-white/80">{entry.value}%</span></div>)}</div></div></section>
      <section data-testid="analytics-reports-panel" className="glass-panel rounded-[26px] p-5 sm:p-6"><div className="flex items-center justify-between"><div><span className="section-kicker">Reports</span><h2 className="mt-2 text-xl font-semibold tracking-tight">Field notes & follow-ups</h2></div><Button type="button" data-testid="analytics-inline-export-button" onClick={() => void exportReport()} disabled={exporting} variant="outline" className="h-9 rounded-xl border-white/10 bg-white/[0.04] text-[10px] text-white/60 hover:bg-white/10"><Download size={14} /> Export PDF</Button></div><div className="mt-5 space-y-3">{analytics.reports.map((report) => <div key={report.id} className="report-row"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edb06c]/10 text-[#edb06c]"><FileText size={15} /></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium text-white/85">{report.title}</div><div className="mt-1 text-[10px] text-white/35">{report.category} · {report.created}</div><div className="mt-1 text-[10px] text-white/35">{report.note}</div></div></div>)}</div></section>
    </div>
    <div className="mt-5 flex items-center gap-2 text-[10px] text-white/30"><Badge variant="outline" className="border-white/10 text-[9px] text-white/40">Model v2.4</Badge> Measurements are frame-synced and reviewable.</div>
  </div></main>;
}
