import { useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { AlertTriangle, CheckCircle2, ImagePlus, MapPin, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { issuesApi } from "@/api/issues";
import type { RoadLocation } from "@/types";

interface IssueModalProps { open: boolean; onClose: () => void; }

export function IssueModal({ open, onClose }: IssueModalProps) {
  const [category, setCategory] = useState("Surface damage");
  const [description, setDescription] = useState("");
  const [attachmentName, setAttachmentName] = useState("");
  const [location] = useState<RoadLocation | undefined>(undefined);
  const [stage, setStage] = useState<"form" | "processing" | "success">("form");
  const submit = async () => { setStage("processing"); await issuesApi.submit({ description, category, attachmentName, location }); window.setTimeout(() => setStage("success"), 700); };
  const close = () => { setStage("form"); setDescription(""); setAttachmentName(""); onClose(); };
  return <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} data-testid="issue-modal" className="fixed inset-0 z-50 flex items-end justify-center bg-black/55 p-3 backdrop-blur-sm sm:items-center sm:p-6"><motion.div initial={{ opacity: 0, y: 28, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 20, scale: 0.98 }} transition={{ type: "spring", stiffness: 360, damping: 30 }} className="w-full max-w-lg overflow-hidden rounded-[28px] border border-white/15 bg-[#17211f]/95 shadow-2xl backdrop-blur-2xl">
    <div className="flex items-start justify-between border-b border-white/10 px-5 py-5 sm:px-6"><div><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#edb06c]"><AlertTriangle size={13} /> Quality loop</div><h2 data-testid="issue-modal-title" className="mt-2 text-xl font-semibold tracking-tight text-white">Report an issue</h2><p className="mt-1 text-xs text-white/45">Help us keep the road model honest.</p></div><button type="button" data-testid="issue-modal-close-button" aria-label="Close report issue" onClick={close} className="text-white/45 transition-colors hover:text-white"><X size={18} /></button></div>
    {stage === "form" && <div className="space-y-5 p-5 sm:p-6"><div><label className="mb-2 block text-xs font-medium text-white/70" htmlFor="issue-category">Defect category</label><select id="issue-category" data-testid="issue-category-select" value={category} onChange={(event) => setCategory(event.target.value)} className="h-10 w-full rounded-xl border border-white/10 bg-white/[0.06] px-3 text-sm text-white outline-none"><option className="bg-[#17211f]">Surface damage</option><option className="bg-[#17211f]">Road markings</option><option className="bg-[#17211f]">Drainage</option><option className="bg-[#17211f]">Safety concern</option></select></div><div><label className="mb-2 block text-xs font-medium text-white/70" htmlFor="issue-description">What did you notice?</label><Textarea id="issue-description" data-testid="issue-description-input" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe the issue and where it appears in the footage..." className="min-h-24 resize-none border-white/10 bg-white/[0.06] text-sm text-white placeholder:text-white/30" /></div><label data-testid="issue-attachment-dropzone" className="flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-white/15 bg-white/[0.03] p-4 transition-colors hover:border-[#b8e986]/50"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/[0.07] text-white/60"><ImagePlus size={17} /></span><span className="flex-1"><span className="block text-xs font-medium text-white/80">{attachmentName || "Attach photo or video"}</span><span className="mt-1 block text-[10px] text-white/35">Optional · JPG, PNG or MP4</span></span><input data-testid="issue-attachment-input" type="file" accept="image/*,video/*" className="sr-only" onChange={(event) => setAttachmentName(event.target.files?.[0]?.name ?? "")} /></label><div className="flex items-center gap-2 text-[11px] text-white/35"><MapPin size={13} /> Location will use the active project pin</div><Button data-testid="issue-submit-button" type="button" onClick={() => void submit()} disabled={!description.trim()} className="h-11 w-full rounded-xl bg-[#edb06c] text-[#21170e] hover:bg-[#f7c98c]">Submit report</Button></div>}
    {stage === "processing" && <div data-testid="issue-processing-state" className="flex min-h-[320px] flex-col items-center justify-center px-8 text-center"><div className="processing-orbit mb-6"><span /></div><h3 className="text-lg font-semibold text-white">Sending your report</h3><p className="mt-2 text-sm text-white/45">Attaching context from the active road survey.</p></div>}
    {stage === "success" && <div data-testid="issue-success-state" className="flex min-h-[320px] flex-col items-center justify-center px-8 text-center"><div className="mb-6 flex h-14 w-14 items-center justify-center rounded-full bg-[#b8e986]/15 text-[#b8e986]"><CheckCircle2 size={28} /></div><h3 className="text-lg font-semibold text-white">Report received</h3><p className="mt-2 max-w-xs text-sm leading-6 text-white/45">Thank you. The RoadRead team will review this frame in the next model pass.</p><Button data-testid="issue-done-button" type="button" onClick={close} className="mt-7 rounded-xl bg-white text-[#10201b] hover:bg-white/90">Done</Button></div>}
  </motion.div></motion.div>}</AnimatePresence>;
}
