import { useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, ChevronLeft, ChevronRight, FileVideo, FolderOpen, Plus, UploadCloud, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { Project, RoadLocation } from "@/types";

interface OnboardingViewProps { projects: Project[]; onExisting: (project: Project) => void; onCreate: (name: string, fileName: string, location: RoadLocation | null, file: File | null) => void; }
export function OnboardingView({ projects, onExisting, onCreate }: OnboardingViewProps) {
  const [step, setStep] = useState<"choice" | "upload">("choice");
  const [fileName, setFileName] = useState("");
  const [projectName, setProjectName] = useState("Udupi Municipal Roads");
  const fileInput = useRef<HTMLInputElement>(null);
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [projectPage, setProjectPage] = useState(1);
  const PROJECTS_PER_PAGE = 5;
  const totalProjectPages = Math.max(1, Math.ceil(projects.length / PROJECTS_PER_PAGE));
  const visibleProjects = useMemo(() => projects.slice((projectPage-1)*PROJECTS_PER_PAGE, projectPage*PROJECTS_PER_PAGE), [projects, projectPage]);
  const handleFile=(file:File|undefined)=>{if(file){setFileName(file.name);setUploadedFile(file);}};
  const goToProjectPage=(page:number)=>setProjectPage(Math.min(totalProjectPages,Math.max(1,page)));
  return <main data-testid="onboarding-screen" className="min-h-svh bg-[#0a1110] px-5 py-8 text-white sm:px-10"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="brand-mark">R</span><span className="text-[13px] font-semibold tracking-[0.24em]">ROADREAD</span></div><div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.16em] text-white/35"><span className={step === "choice" ? "step-dot step-dot-active" : "step-dot"}>01</span><span className="hidden sm:inline">Workspace setup</span><span className="step-line"/><span className={step === "upload" ? "step-dot step-dot-active" : "step-dot"}>02</span><span className="hidden sm:inline">Survey source</span></div></header>
  {step === "choice" && <section className="mx-auto max-w-4xl py-20 sm:py-28"><div className="mb-12"><p className="mb-4 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#b8e986]">Good morning, Arjun</p><h1 className="max-w-2xl text-5xl font-semibold leading-[0.96] tracking-[-0.06em] sm:text-7xl">What would you like<br/><span className="text-white/35">to work on?</span></h1><p className="mt-6 max-w-md text-sm leading-6 text-white/45">Choose a live survey or start a new analysis from footage captured on the road.</p></div><div className="grid gap-5 md:grid-cols-2"><button type="button" data-testid="create-new-project-option" onClick={()=>setStep("upload")} className="choice-card group text-left"><span className="choice-icon bg-[#b8e986] text-[#0c1c17]"><Plus size={20}/></span><span className="mt-8 block text-xl font-semibold">Create new project</span><span className="mt-2 block max-w-xs text-sm leading-6 text-white/45">Upload a road survey and start analysis directly.</span><span className="mt-10 flex items-center gap-2 text-xs font-medium text-[#b8e986]">Start fresh <ArrowRight size={14}/></span></button><div data-testid="existing-projects-panel" className="choice-card"><div className="flex items-center justify-between"><span className="choice-icon bg-white/10 text-white"><FolderOpen size={19}/></span><span className="text-[10px] uppercase tracking-[0.16em] text-white/35">{projects.length} active</span></div><span className="mt-8 block text-xl font-semibold">Continue existing</span><span className="mt-2 block text-sm leading-6 text-white/45">Open a recent project and return to its road intelligence.</span><div className="mt-6 space-y-1">{visibleProjects.map(p=><button key={p.id} type="button" data-testid={`existing-project-${p.id}-button`} onClick={()=>onExisting(p)} className="project-row"><span><span className="block text-left text-xs font-medium text-white/85">{p.name}</span><span className="mt-1 block text-left text-[10px] text-white/35">{p.updated}</span></span><Badge variant="outline" className="border-white/10 text-[9px] text-white/45">{p.status}</Badge></button>)}</div><div className="mt-4 flex items-center justify-between border-t border-white/[0.07] pt-3"><span className="text-[10px] text-white/30">Page {projectPage} of {totalProjectPages} · {projects.length} projects</span><div className="flex items-center gap-1"><button type="button" disabled={projectPage===1} onClick={()=>goToProjectPage(projectPage-1)} className="flex h-8 w-8 items-center justify-center rounded-lg border border-white/10 text-white/45 disabled:opacity-25"><ChevronLeft size={14}/></button><button type="button" disabled={projectPage===totalProjectPages} onClick={()=>goToProjectPage(projectPage+1)} className="flex h-8 w-8 items-center justify-center rounded-lg border border-white/10 text-white/45 disabled:opacity-25"><ChevronRight size={14}/></button></div></div></div></div></section>}
  {step === "upload" && <section className="mx-auto max-w-3xl py-16 sm:py-24"><button type="button" onClick={()=>setStep("choice")} className="mb-12 flex items-center gap-2 text-xs text-white/40 hover:text-white"><ArrowLeft size={14}/> Back to projects</button><p className="mb-4 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#b8e986]">New road survey</p><h1 className="text-5xl font-semibold leading-none tracking-[-0.06em] sm:text-7xl">Bring the road<br/><span className="text-white/35">into focus.</span></h1><div className="mt-12 space-y-5"><label className="block"><span className="mb-2 block text-xs font-medium text-white/60">Project name</span><input data-testid="project-name-input" value={projectName} onChange={e=>setProjectName(e.target.value)} className="h-12 w-full rounded-xl border border-white/10 bg-white/[0.05] px-4 text-sm text-white outline-none focus:border-[#b8e986]/60"/></label><button type="button" data-testid="upload-dropzone" onClick={()=>fileInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();handleFile(e.dataTransfer.files[0]);}} className="upload-zone group w-full text-left"><input ref={fileInput} data-testid="project-file-input" type="file" accept="video/*,image/*" className="sr-only" onChange={e=>handleFile(e.target.files?.[0])}/><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#b8e986]/10 text-[#b8e986]">{fileName?<FileVideo size={22}/>:<UploadCloud size={22}/>}</span><span className="ml-4 flex-1"><span className="block text-sm font-medium text-white">{fileName||"Drop road footage here"}</span><span className="mt-1 block text-xs text-white/35">MP4, MOV, JPG or PNG · up to 2 GB</span></span><span className="rounded-lg border border-white/10 px-3 py-2 text-[10px] font-medium text-white/60">Browse</span></button>{fileName&&<div className="flex items-center gap-3 rounded-xl border border-[#b8e986]/20 bg-[#b8e986]/[0.06] p-3 text-xs text-[#d9ffc4]"><Check size={15}/>{fileName} · ready for analysis</div>}<Button data-testid="start-analysis-button" type="button" onClick={()=>onCreate(projectName,fileName,null,uploadedFile)} disabled={!fileName} className="h-12 w-full rounded-xl bg-[#b8e986] text-[#10201b] hover:bg-[#d2f7ae]"><ArrowRight size={16}/> Start RoadRead analysis</Button><p className="text-center text-[10px] text-white/30">Location is optional and can be added later to the project.</p></div></section>}</div></main>;
}
